
Bad Request: /users/signup-mobile/
Bad Request: /users/signup-mobile/
Bad Request: /users/signup-mobile/
Bad Request: /users/signup-mobile/
Bad Request: /users/signup-mobile/
Failed to send OTP, 400
Internal Server Error: /users/signup-mobile/
Traceback (most recent call last):
  File "C:\Users\Anand\.virtualenvs\Registration-2zT5uEZH\lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "C:\Users\Anand\.virtualenvs\Registration-2zT5uEZH\lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\Anand\.virtualenvs\Registration-2zT5uEZH\lib\site-packages\django\views\decorators\csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
  File "C:\Users\Anand\.virtualenvs\Registration-2zT5uEZH\lib\site-packages\django\views\generic\base.py", line 103, in view
    return self.dispatch(request, *args, **kwargs)
  File "C:\Users\Anand\.virtualenvs\Registration-2zT5uEZH\lib\site-packages\rest_framework\views.py", line 511, in dispatch
    self.response = self.finalize_response(request, response, *args, **kwargs)
  File "C:\Users\Anand\.virtualenvs\Registration-2zT5uEZH\lib\site-packages\rest_framework\views.py", line 423, in finalize_response
    assert isinstance(response, HttpResponseBase), (
AssertionError: Expected a `Response`, `HttpResponse` or `HttpStreamingResponse` to be returned from the view, but received a `<class 'NoneType'>`
Sent Successfully, 200
Sent Successfully, Status=200
Sent Successfully, Status=200
Failed to send OTP, Status=400
Internal Server Error: /users/signup-mobile/
Traceback (most recent call last):
  File "C:\Users\Anand\.virtualenvs\Registration-2zT5uEZH\lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "C:\Users\Anand\.virtualenvs\Registration-2zT5uEZH\lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\Anand\.virtualenvs\Registration-2zT5uEZH\lib\site-packages\django\views\decorators\csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
  File "C:\Users\Anand\.virtualenvs\Registration-2zT5uEZH\lib\site-packages\django\views\generic\base.py", line 103, in view
    return self.dispatch(request, *args, **kwargs)
  File "C:\Users\Anand\.virtualenvs\Registration-2zT5uEZH\lib\site-packages\rest_framework\views.py", line 511, in dispatch
    self.response = self.finalize_response(request, response, *args, **kwargs)
  File "C:\Users\Anand\.virtualenvs\Registration-2zT5uEZH\lib\site-packages\rest_framework\views.py", line 423, in finalize_response
    assert isinstance(response, HttpResponseBase), (
AssertionError: Expected a `Response`, `HttpResponse` or `HttpStreamingResponse` to be returned from the view, but received a `<class 'NoneType'>`
Sent Successfully, Status=200
Sent Successfully, Status=200
Sent Successfully, Status=200
Failed to send OTP, Status=400
Internal Server Error: /users/signup-mobile/
Traceback (most recent call last):
  File "C:\Users\Anand\.virtualenvs\Registration-2zT5uEZH\lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "C:\Users\Anand\.virtualenvs\Registration-2zT5uEZH\lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\Anand\.virtualenvs\Registration-2zT5uEZH\lib\site-packages\django\views\decorators\csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
  File "C:\Users\Anand\.virtualenvs\Registration-2zT5uEZH\lib\site-packages\django\views\generic\base.py", line 103, in view
    return self.dispatch(request, *args, **kwargs)
  File "C:\Users\Anand\.virtualenvs\Registration-2zT5uEZH\lib\site-packages\rest_framework\views.py", line 511, in dispatch
    self.response = self.finalize_response(request, response, *args, **kwargs)
  File "C:\Users\Anand\.virtualenvs\Registration-2zT5uEZH\lib\site-packages\rest_framework\views.py", line 423, in finalize_response
    assert isinstance(response, HttpResponseBase), (
AssertionError: Expected a `Response`, `HttpResponse` or `HttpStreamingResponse` to be returned from the view, but received a `<class 'NoneType'>`
Failed to send OTP The `request` argument must be an instance of `django.http.HttpRequest`, not `builtins.str`., Status=400
Bad Request: /users/signup-mobile/
Failed to send OTP, Status=400
Internal Server Error: /users/signup-mobile/
Traceback (most recent call last):
  File "C:\Users\Anand\.virtualenvs\Registration-2zT5uEZH\lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "C:\Users\Anand\.virtualenvs\Registration-2zT5uEZH\lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\Anand\.virtualenvs\Registration-2zT5uEZH\lib\site-packages\django\views\decorators\csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
  File "C:\Users\Anand\.virtualenvs\Registration-2zT5uEZH\lib\site-packages\django\views\generic\base.py", line 103, in view
    return self.dispatch(request, *args, **kwargs)
  File "C:\Users\Anand\.virtualenvs\Registration-2zT5uEZH\lib\site-packages\rest_framework\views.py", line 511, in dispatch
    self.response = self.finalize_response(request, response, *args, **kwargs)
  File "C:\Users\Anand\.virtualenvs\Registration-2zT5uEZH\lib\site-packages\rest_framework\views.py", line 423, in finalize_response
    assert isinstance(response, HttpResponseBase), (
AssertionError: Expected a `Response`, `HttpResponse` or `HttpStreamingResponse` to be returned from the view, but received a `<class 'NoneType'>`
Failed to send OTP, Status=400
Bad Request: /users/signup-mobile/
Failed to send OTP, Status=400
Internal Server Error: /users/signup-mobile/
Traceback (most recent call last):
  File "C:\Users\Anand\.virtualenvs\Registration-2zT5uEZH\lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "C:\Users\Anand\.virtualenvs\Registration-2zT5uEZH\lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\Anand\.virtualenvs\Registration-2zT5uEZH\lib\site-packages\django\views\decorators\csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
  File "C:\Users\Anand\.virtualenvs\Registration-2zT5uEZH\lib\site-packages\django\views\generic\base.py", line 103, in view
    return self.dispatch(request, *args, **kwargs)
  File "C:\Users\Anand\.virtualenvs\Registration-2zT5uEZH\lib\site-packages\rest_framework\views.py", line 511, in dispatch
    self.response = self.finalize_response(request, response, *args, **kwargs)
  File "C:\Users\Anand\.virtualenvs\Registration-2zT5uEZH\lib\site-packages\rest_framework\views.py", line 423, in finalize_response
    assert isinstance(response, HttpResponseBase), (
AssertionError: Expected a `Response`, `HttpResponse` or `HttpStreamingResponse` to be returned from the view, but received a `<class 'NoneType'>`
Failed to send OTP response_with_logger() got an unexpected keyword argument 'status', Status=400
Bad Request: /users/signup-mobile/
Sent Successfully, Status=200
Sent Successfully, Status=200
Sent Successfully, Status=200
Failed to send OTP response_with_logger() got an unexpected keyword argument 'status', Status=400
Bad Request: /users/signup-mobile/
